In [1]:
import pandas as pd

df = pd.read_csv('trucks.csv')
df

,seq,type,timestamp,truckId,positionLatitude,positionLongitude,equipType,nextTripLengthPreference
0,15,Truck,2023-11-17T08:12:28,101,34.294167,-85.879997,Reefer,Long
1,16,Truck,2023-11-17T08:19:59,134,39.913216,-86.210175,Flatbed,Short
2,17,Truck,2023-11-17T08:20:41,121,36.077549,-87.120148,Van,Short
3,19,Truck,2023-11-17T08:28:02,106,32.505447,-85.605026,Van,Long
4,20,Truck,2023-11-17T08:29:42,147,35.794121,-86.377892,Flatbed,Long
...,...,...,...,...,...,...,...,...
1995,2496,Truck,2023-11-17T22:58:03,238,42.132271,-72.051010,Reefer,Short
1996,2497,Truck,2023-11-17T22:59:24,353,42.473766,-79.276031,Flatbed,Short
1997,2498,Truck,2023-11-17T22:59:27,290,39.569466,-76.139107,Van,Short
1998,2499,Truck,2023-11-17T22:59:35,241,38.293682,-85.542076,Flatbed,Long
1999,2500,Truck,2023-11-17T22:59:56,237,37.807678,-80.408539,Van,Short

In [4]:
serie = df['truckId'].value_counts()
serie

366    19
106    14
292    14
110    14
331    14
       ..
123     1
400     1
197     1
219     1
222     1
Name: truckId, Length: 322, dtype: int64

In [5]:
df.loc[df['truckId'] == 366]

,seq,type,timestamp,truckId,positionLatitude,positionLongitude,equipType,nextTripLengthPreference
233,362,Truck,2023-11-17T10:56:38,366,41.966702,-70.694420,Reefer,Short
472,708,Truck,2023-11-17T12:33:50,366,41.925396,-71.327072,Reefer,Short
542,802,Truck,2023-11-17T13:03:56,366,41.650585,-71.610458,Reefer,Short
553,821,Truck,2023-11-17T13:08:54,366,41.591705,-71.660004,Reefer,Short
577,856,Truck,2023-11-17T13:18:55,366,41.465271,-71.766190,Reefer,Short
605,896,Truck,2023-11-17T13:33:58,366,41.362232,-72.026932,Reefer,Short
660,989,Truck,2023-11-17T13:58:59,366,41.292206,-72.449394,Reefer,Short
670,1004,Truck,2023-11-17T14:03:59,366,41.288151,-72.551048,Reefer,Short
713,1089,Truck,2023-11-17T14:22:49,366,41.290794,-72.587166,Reefer,Short
758,1156,Truck,2023-11-17T14:37:49,366,41.338730,-72.798958,Reefer,Short
834,1258,Truck,2023-11-17T15:12:10,366,41.429733,-72.846733,Reefer,Short
1332,1826,Truck,2023-11-17T18:07:54,366,41.175385,-73.166466,Reefer,Short
1663,2158,Truck,2023-11-17T20:09:38,366,40.844151,-73.898552,Reefer,Short
1739,2239,Truck,2023-11-17T20:39:44,366,40.822334,-74.035416,Reefer,Short
1815,2315,Truck,2023-11-17T21:19:46,366,40.599945,-74.269753,Reefer,Short
1824,2324,Truck,2023-11-17T21:24:49,366,40.563160,-74.300308,Reefer,Short
1840,2340,Truck,2023-11-17T21:34:49,366,40.540020,-74.387047,Reefer,Short
1903,2403,Truck,2023-11-17T22:03:45,366,40.642769,-74.869438,Reefer,Short
1968,2468,Truck,2023-11-17T22:38:48,366,40.570343,-75.402435,Reefer,Short